data1={
"id": 4,
"name": "Guns N Petals",
"genres": ["Rock n Roll"],
"city": "San Francisco",
"state": "CA",
"phone": "326-123-5000",
"website": "https://www.gunsnpetalsband.com",
"facebook_link": "https://www.facebook.com/GunsNPetals",
"seeking_venue": True,
"seeking_description": "Looking for shows to perform at in the San Francisco Bay Area!",
"image_link": "https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80",
}

GET  http://localhost:5000/artists HTTP/1.1
content-type: application/json

{
    "id": 4,
    "name": "Guns N Petals",
    "genres": ["Rock n Roll"],
    "city": "San Francisco",
    "state": "CA",
    "phone": "326-123-5000",
    "website": "https://www.gunsnpetalsband.com",
    "facebook_link": "https://www.facebook.com/GunsNPetals",
    "seeking_venue": True,
    "seeking_description": "Looking for shows to perform at in the San Francisco Bay Area!",
    "image_link": "https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80"
}